/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CJlHcGVWFrn
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Track } from "@prisma/client";

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function DissContent({ tracks }: { tracks: Track[] }) {
  return (
    <div className="grid md:grid-cols-1 gap-8 max-w-6xl mx-auto py-12 px-4">
      <div>
        <div className="aspect-video rounded-lg overflow-hidden" />
        <div className="mt-6 space-y-4">
          <h1 className="text-3xl font-bold">The Ultimate Diss Track</h1>
          <p className="text-gray-500 dark:text-gray-400">
            This diss track is the most savage thing you'll ever hear. Get ready
            to be blown away.
          </p>
        </div>
      </div>
      <div className="space-y-6">
        <h2 className="text-2xl font-bold">Response Videos</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-24 h-16 rounded-lg overflow-hidden">
              <img
                alt="Response Video Thumbnail"
                className="w-full h-full object-cover"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "96/64",
                  objectFit: "cover",
                }}
                width={96}
              />
            </div>
            <div className="flex-1">
              <h3 className="text-lg font-medium">The Ultimate Clapback</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                You won't believe how hard this guy hits back. This is a
                must-watch.
              </p>
            </div>
          </div>
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-24 h-16 rounded-lg overflow-hidden">
              <img
                alt="Response Video Thumbnail"
                className="w-full h-full object-cover"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "96/64",
                  objectFit: "cover",
                }}
                width={96}
              />
            </div>
            <div className="flex-1">
              <h3 className="text-lg font-medium">The Savage Rebuttal</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                This response is so good, it'll make you question everything you
                know.
              </p>
            </div>
          </div>
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-24 h-16 rounded-lg overflow-hidden">
              <img
                alt="Response Video Thumbnail"
                className="w-full h-full object-cover"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "96/64",
                  objectFit: "cover",
                }}
                width={96}
              />
            </div>
            <div className="flex-1">
              <h3 className="text-lg font-medium">The Epic Comeback</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                You won't believe how this guy turns the tables. This is a
                must-see.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
